name: Deploy to S3 via Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get bucket name from Terraform output
        id: bucket
        run: |
          echo "bucket_name=$(terraform output -raw bucket_name | tr -d '\n')" >> "$GITHUB_OUTPUT"
        working-directory: ./terraform

      - name: Debug bucket name
        run: echo "Bucket name is: ${{ steps.bucket.outputs.bucket_name }}"

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          echo "Syncing to bucket: ${{ steps.bucket.outputs.bucket_name }}"
          aws s3 sync ./dist s3://${{ steps.bucket.outputs.bucket_name }} --delete --acl public-read
